fields:

    _title:
        label: Title
        comment: Description
        type: section

    copy:
        type: nestedform
        form: ~/themes/test-theme/config/pages-header-copy.yaml
        span: left

    image:
        label: Image
        type: mediafinder
        required: true
        mode: image
        span: right

    button[label]:
        label: Button Label
        commentAbove: Add some text for the button label
        type: text
        span: right
